// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tckkrwlsylidpmzjrcvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRja2tyd2xzeWxpZHBtempyY3Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTMzNjgsImV4cCI6MjA2NDAyOTM2OH0._jpHLzOkNPFUME-DcRVY2OkA6BwFbSUtZK66xHVtrWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);